apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
    tier: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      tier: postgres
  template:
    metadata:
      labels:
        app: postgres
        tier: postgres
    spec:
      containers:
        - name: postgres-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: testdb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
      restartPolicy: Always