version: "3.1"
services:
  backend:
    build:
      context: .
    container_name: backend
    depends_on:
      - test-postgres-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://testdb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  test-postgres-service:
    image: "postgres:latest"
    container_name: "testdb"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  pgadmin-service:
    image: "dpage/pgadmin4"
    container_name: "pgadmin2"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "82:80"
