name: docker-build-and-push

on:
  push:
    branches:
      - 'kube'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          docker build -t ile1337/backend ./backend
          docker push ile1337/backend
  deploy:
        needs: build
        runs-on:
            - self-hosted
            - label-1
        steps:
            - uses: actions/checkout@v2
            
            - name: Run scripts
              run: |
                cd ../backend
                git pull origin kube
                git checkout kube
                cd kube
                helm upgrade --install database-chart database-chart
                helm upgrade --install backend-chart backend-chart
                kubectl rollout restart deployment backenddeployment
